### ISSUE TITLE
Replace Thread.Sleep() calls with safer/better alternatives

### ISSUE THREAD

**Issue by tjaskula** [vlingo-net/vlingo-net-actors#26]
There are many calls to `Thread.Sleep` which is not the best alternative in concurrent code.

**Comment by VaughnVernon** [comment]
@tjaskula Can you indicate where the Thread.Sleep() uses are? There may be a few in tests, which is not the greatest choice, and will inevitably fail. However, there should pretty much never be Thread.Sleep() in the library code. I think there may be one possible use of Thread.Sleep() when the World is terminating. I don't remember. In such case it could still be replaced with a better construct as you suggest.

**Comment by tjaskula** [comment]
Except tests there are actualy two places in:

- Backoff class https://github.com/vlingo-net/vlingo-net-actors/blob/c8c47d2d94dc6b8674ea7890ec2a9c3346046ce8/src/Vlingo.Actors/Backoff.cs#L59
- Stage class https://github.com/vlingo-net/vlingo-net-actors/blob/61c6d4c908638d29e4284d5188fd017aac1a0e8a/src/Vlingo.Actors/Stage.cs#L274

**Comment by VaughnVernon** [comment]
@tjaskula Yes, thanks for the reminder. I would be perfectly happy if both of these `Sleep()` uses went away. Eventually `Stop()` will be async in that the `Sweep()` will be actor-based and return immediately. At that point we will need an atomic indicator that `Sweep()` and `Stop()` have fully completed, and we will need to aggregate that indicator into a single one when stopping multiple `Stage` containers. (The default container is always created, but the application/service can start any number of others.)

**Comment by tjaskula** [comment]
I’ll take care of that

**Comment by tjaskula** [comment]
`Backoff` is addressed in #29

**Comment by tjaskula** [comment]
@zpbappi @VaughnVernon Why we need that when stopping a stage in `Stage.Stop()`:

```
while (Count > 1 && ++retries < 10)
            {
                try { Thread.Sleep(10); } catch (Exception) { }
            }
```

**Comment by tjaskula** [comment]
This is not more relevant
