### ISSUE TITLE
Update NuGet Package informations in .csproj

### ISSUE THREAD

**Issue by tjaskula** [vlingo-net/vlingo-net-actors#32]
`PackageLicenseUrl` is deprecated. Now we should use `PackageLicenseFile`.

Also we need to update other properties like tags, etc.

**Comment by tjaskula** [comment]
@zpbappi Could you confirm if this issue can be closed ?

**Comment by zpbappi** [comment]
It will be fixed when I push my changes. Not yet.

**Comment by tjaskula** [comment]
@zpbappi fixed ?
