### ISSUE TITLE
Investigate randomly failing tests after new BasicCompletes implementation

### ISSUE THREAD

**Issue by tjaskula** [vlingo-net/vlingo-net-actors#63]
I have noticed that there is still a slight issue as it comes to the execution of the pipeline in the multi threaded environment. These are not blocking but the investigation should be done along with a fix to be sure that everything behaves consistently.

On CI server:

 - `TestThatManyScheduleOnceDeliver` never completes. https://ci.appveyor.com/project/VlingoNetOwner/vlingo-net-actors/builds/28113803/tests
 - `TestThatTimeOutOccursForSideEffects` mail fail https://ci.appveyor.com/project/VlingoNetOwner/vlingo-net-actors/builds/28113878/tests
 
Locally on Windows machine:
 - `TestAfterAndThenCompletesForSideEffects` 
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Vlingo.Actors.Tests.CompletesActorProtocolTest.TestAfterAndThenCompletesForSideEffects() in C:\Sources\GitHub\vlingo-net-actors\src\Vlingo.Actors.Tests\CompletesActorProtocolTest.cs:line 48
```
 - `TestReturnsCompletesForSideEffects` freezes
 - `TestSupplierProtocol` freezes
 - `TestTwoArgConsumerProtocol`.

I suspect those might be the problem of continuation not being executed immediately if the outcome is set for the main continuation.

**Comment by tjaskula** [comment]
The suspicion about the scheduled continuation not being executed immediately was right. Under some circumstances the scheduled continuation takes far more time to being scheduled on the thread look thread. This is especially true on Travis where VMs seems to be very busy.

**Comment by mihaj** [comment]
Have you tried Azure DevOps? They offer 10 parallel agents for open source projects.

**Comment by tjaskula** [comment]
Always good to have busy machines. It tests differently :)
