### ISSUE TITLE
Type-safe constructor for Actor creation

### ISSUE THREAD

**Issue by tjaskula** [vlingo-net/vlingo-net-actors#81]
Today we crate the actor by the following way:

```
var definition =
                Definition.Has<InboundStreamActor>(Definition.Parameters(interest, addressType, reader, probeInterval),$"{inboundName}-inbound");
var inboundStream = stage.ActorFor<IInboundStream>(definition);
```

The goal would be to create the actor in the type-safe manner. Why ? Because it easier to be guided by the compiler what parameters to pass in the actor based on the type of actor. Instead we could do the following

```
var inboundStream = stage.ActorFor<IInboundStream>(() => new InboundStreamActor(interest, addressType, reader, probeInterval),$"{inboundName}-inbound"))
```

For that we would need to leverage creation through expressions like:

```
ActorFor<TActor>(Expression<Func<TActor>> factor)
```

For reference on JVM implementation (for impacted files rather than implementation details) : https://github.com/vlingo/vlingo-actors/commit/141f31b926e9534b2306c2768bdd4eefa3e2d519

**Comment by VaughnVernon** [comment]
@tjaskula I agree with this. Another way is to use an `ActorInstantiator` pattern. Currently in vlingo-java you can use a `ActorInstantiator` as a single lambda expression, because it is a `@FunctionalInterface`.

`() -> new InboundStreamActor(interest, addressType, reader, probeInterval)`

You can do this for the `actorFor()` that has the overload for an `ActorInstantiator`.

**Comment by tjaskula** [comment]
@VaughnVernon you mean that you pass `() -> new InboundStreamActor(interest, addressType, reader, probeInterval)`inside the `actorFor()` right ?

**Comment by VaughnVernon** [comment]
@tjaskula Correct.

**Comment by tjaskula** [comment]
Yes, so this should be similar to what I'm going to use on .NET side :)

**Comment by VaughnVernon** [comment]
Oh, ok. The above looked more verbose to me. I see now that I missed this code:

`var inboundStream = stage.ActorFor<IInboundStream>(() => new InboundStreamActor(interest, addressType, reader, probeInterval),$"{inboundName}-inbound"))`
